const CATALOGUE_CATEGORIES=[
  "One sound crackers",
  "ANUKUNDU",
  "PAPER BOMB",
  "BIJILI",
  "WAR",
  "DIGITAL WALA",
  "Flower Pots",
  "Tri Colour Pots",
  "Ground chakkar",
  "Elite chakkar",
  "Twinkling Star",
  "Rocket series",
  "Kutty's Series",
  "Skyking Brand Fountain",
  "Skyking Candle",
  "Vanitha Special",
  "Vadivel Special",
  "Starvel Special",
  "Multicolour Shots",
  "One Shot Fancy",
  "3½ fancy",
  "4 Fancy",
  "5 Fancy",
  "Peacock Series",
  "Sparklers",
  "Elite crackers",
  "Matches",
  "Gift Boxes"
];
